### ISSUE TITLE
 TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by MarcSkovMadsen** [RandomFractals/vscode-data-preview#204]
Hi Tarak

Tried installing the data previewer extension in VS Code. But I got the below error when trying to "preview" a csv file. I found the error in the `Log (Extension Host)`

```ts
[2020-05-25 10:48:01.464] [exthost] [info] ExtensionService#_doActivateExtension RandomFractalsInc.vscode-data-preview {"startup":false,"extensionId":{"value":"RandomFractalsInc.vscode-data-preview","_lower":"randomfractalsinc.vscode-data-preview"},"activationEvent":"onLanguage:csv"}
[2020-05-25 10:48:01.464] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/masma/.vscode/extensions/randomfractalsinc.vscode-data-preview-2.0.0/out/extension
[2020-05-25 10:48:02.831] [exthost] [error] TypeError: Cannot read property 'startsWith' of undefined
    at DataPreview.get theme [as theme] (c:\Users\masma\.vscode\extensions\randomfractalsinc.vscode-data-preview-2.0.0\out\data.preview.js:752:21)
    at new DataPreview (c:\Users\masma\.vscode\extensions\randomfractalsinc.vscode-data-preview-2.0.0\out\data.preview.js:110:44)
    at c:\Users\masma\.vscode\extensions\randomfractalsinc.vscode-data-preview-2.0.0\out\extension.js:109:25
    at _executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:549:220)
    at _.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:549:595)
    at p._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:688:464)
    at p._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:688:156)
    at p._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:686:817)
    at p._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:685:623)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:683:791
    at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
    at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:325)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:851:104
    at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
    at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:325)
    at t.PersistentProtocol._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:195:717)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:192:897
    at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:845)
    at p.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:897)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:249
    at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:197:232)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) data.preview
```

System Info

Version: 1.43.1 (system setup)
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:20.184Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by MarcSkovMadsen** [comment]
After a restart of VS Code. Everything works like a charm.

**Comment by RandomFractals** [comment]
this extension installation and update does require vscode restart.

Provided it worked after restart, I'll close this.

Thanks for checking it out & let me know what features you like the most and what data files you'll be using Data Preview for.

**Comment by MarcSkovMadsen** [comment]
For now my files are primarily CSV
